apiVersion: v1
kind: Service
metadata:
  name: temperature-converter
spec:
  type: LoadBalancer
  selector:
    app: temperature-converter
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
